service: technical-challenge

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

custom:
  dotenvVars: ${file(configs.js)}
  serverless-offline:
    noPrependStageInUrl: true
  optimize:
    external: ['swagger-ui-dist']
  esbuild:
    exclude:
      - "@aws-sdk/*"

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: development
  environment: ${file(configs.js)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:194722424694:table/Person
        - arn:aws:dynamodb:us-west-2:194722424694:table/History
    
functions:
  main:
    handler: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true